<?php
declare(strict_types=1);

namespace EMA\Tests\Infrastructure\Note\Commands\ModifyNote;

use function DI\object;
use EMA\Domain\Note\Model\Collection\NoteCollection;
use EMA\Infrastructure\Note\Collection\DoctrineNoteCollection;
use EMA\Tests\BaseTest;

class ModifyNoteHandlerTest extends \EMA\Tests\Domain\Note\Commands\ModifyNote\ModifyNoteHandlerTest
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        
        $this->restartContainer();
        $this->setAuthorizationAs(true);
        container()->set(NoteCollection::class, object(DoctrineNoteCollection::class));
        
        $this->migrate();
    }
}
