<?php
declare(strict_types=1);

namespace EMA\Tests\Infrastructure\Note\Commands\DeleteNote;


use function DI\object;
use EMA\Domain\Note\Model\Collection\NoteCollection;
use EMA\Infrastructure\Note\Collection\DoctrineNoteCollection;

class DeleteNoteHandlerTest extends \EMA\Tests\Domain\Note\Commands\DeleteNote\DeleteNoteHandlerTest
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        
        $this->restartContainer();
        container()->set(NoteCollection::class, object(DoctrineNoteCollection::class));
        
        $this->migrate();
    }
    
    
}
