<?php
declare(strict_types=1);

namespace EMA\Tests\Infrastructure\Query\SearchNotes;

use function DI\object;
use EMA\App\Note\Query\NoteFinder;
use EMA\Domain\Note\Model\Collection\NoteCollection;
use EMA\Infrastructure\Note\Collection\DoctrineNoteCollection;
use EMA\Infrastructure\Note\Finder\DoctrineNoteFinder;
use EMA\Tests\App\Note\Query\AllNotes\AllNotesHandlerTest;
use EMA\Tests\App\Note\Query\SearchNotes\SearchNotesHandlerTest;

final class DoctrineAllNotesTest extends AllNotesHandlerTest
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        
        container()->set(NoteCollection::class, object(DoctrineNoteCollection::class));
        container()->set(NoteFinder::class, object(DoctrineNoteFinder::class));
        
        $this->migrate();
        
    }
}