<?php
declare(strict_types=1);

namespace EMA\Tests\Domain\Note\Commands\PostNewNote;

use function DI\object;
use EMA\Domain\Foundation\VO\Identity;
use EMA\Domain\Note\Commands\PostNewNote\PostNewNote;
use EMA\Domain\Note\Commands\PostNewNote\PostNewNoteHandler;
use EMA\Domain\Note\Model\Collection\NoteCollection;
use EMA\Domain\Note\Model\VO\NoteText;
use EMA\Infrastructure\Note\Collection\DoctrineNoteCollection;
use EMA\Tests\BaseTest;
use Faker\Factory;

class PostNewNoteHandlerTest extends BaseTest
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        
        $this->restartContainer();
        container()->set(NoteCollection::class, object(DoctrineNoteCollection::class));
        
        $this->migrate();
    }
        
}
